/*
 * Copyright (c) 2026 Bryan C. Everly
 * SPDX-License-Identifier: BSD-2-Clause
 */
#include <fcntl.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

#include "index.h"
#include "json.h"
#include "machine.h"
#include "test.h"

/* Writes `text` to dir/rel, creating the directories on the way. */
static void put(const char *dir, const char *rel, const char *text)
{
    char       *path = rs_xasprintf("%s/%s", dir, rel);
    const char *slash;
    size_t      i;
    int         fd;

    for (i = strlen(dir) + 1; path[i] != '\0'; i++)
    {
        if (path[i] == '/')
        {
            path[i] = '\0';
            (void)mkdir(path, 0755);
            path[i] = '/';
        }
    }
    slash = strrchr(path, '/');
    if (slash && slash[1] == '\0')
    {
        free(path);
        return;   /* a directory only */
    }
    fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    CHECK(fd >= 0);
    if (fd >= 0)
    {
        CHECK(write(fd, text, strlen(text)) == (ssize_t)strlen(text));
        (void)close(fd);
    }
    free(path);
}

static void put_bytes(const char *dir, const char *rel, const unsigned char *data, size_t len)
{
    char *path = rs_xasprintf("%s/%s", dir, rel);
    int   fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);

    CHECK(fd >= 0);
    if (fd >= 0)
    {
        CHECK(write(fd, data, len) == (ssize_t)len);
        (void)close(fd);
    }
    free(path);
}

static void be(unsigned char *p, uint64_t v, int bytes)
{
    int i;

    for (i = bytes - 1; i >= 0; i--)
    {
        p[i] = (unsigned char)(v & 0xff);
        v >>= 8;
    }
}

/* A LUKS2 header with its JSON area, 16 KiB in all. */
static unsigned char *luks2_header(size_t *len)
{
    static const char json[] =
        "{\"tokens\": {\"0\": {\"type\": \"systemd-tpm2\"}, \"1\": {\"keyslots\": []}}, "
        "\"keyslots\": {\"0\": {\"type\": \"luks2\", \"key_size\": 64, "
        "\"area\": {\"type\": \"raw\", \"encryption\": \"aes-xts-plain64\", \"key_size\": 64}, "
        "\"kdf\": {\"type\": \"argon2id\", \"time\": 4}}}, "
        "\"segments\": {\"0\": {\"type\": \"crypt\", \"offset\": \"16777216\", "
        "\"encryption\": \"aes-xts-plain64\", \"sector_size\": 4096}}}";
    unsigned char *h = rs_xcalloc(16384, 1);

    memcpy(h, "LUKS\xba\xbe", 6);
    be(h + 6, 2, 2);
    be(h + 8, 16384, 8);
    memcpy(h + 24, "rootfs", 6);
    memcpy(h + 168, "11111111-2222-3333-4444-555555555555", 36);
    memcpy(h + 4096, json, sizeof(json) - 1);
    *len = 16384;
    return h;
}

static unsigned char *luks1_header(void)
{
    unsigned char *h = rs_xcalloc(1024, 1);

    memcpy(h, "LUKS\xba\xbe", 6);
    be(h + 6, 1, 2);
    memcpy(h + 8, "aes", 3);
    memcpy(h + 40, "cbc-essiv:sha256", 16);
    memcpy(h + 72, "sha1", 4);
    be(h + 108, 32, 4);
    memcpy(h + 168, "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", 36);
    return h;
}

static const char lvm_metadata[] =
    "# Generated by LVM2\n"
    "contents = \"Text Format Volume Group\"\n"
    "version = 1\n"
    "description = \"Created *after* executing 'lvcreate'\"\n"
    "creation_time = 1700000000\t# Tue Nov 14 2023\n"
    "\n"
    "vg0 {\n"
    "\tid = \"abcdef-1234\"\n"
    "\tseqno = 3\n"
    "\tstatus = [\"RESIZEABLE\", \"READ\", \"WRITE\"]\n"
    "\textent_size = 8192\n"
    "\tphysical_volumes {\n"
    "\t\tpv0 {\n"
    "\t\t\tid = \"pv-uuid\"\n"
    "\t\t\tdevice = \"/dev/mapper/sda2_crypt\"\n"
    "\t\t\tdev_size = 2088960\n"
    "\t\t\tpe_count = 254\n"
    "\t\t}\n"
    "\t}\n"
    "\tlogical_volumes {\n"
    "\t\troot-lv.1+x {\n"
    "\t\t\tid = \"lv-uuid\"\n"
    "\t\t\tsegment_count = 1\n"
    "\t\t\tsegment1 {\n"
    "\t\t\t\tstart_extent = 0\n"
    "\t\t\t\textent_count = 200\n"
    "\t\t\t\ttype = \"striped\"\n"
    "\t\t\t\tstripes = [\n\t\t\t\t\t\"pv0\", 0\n\t\t\t\t]\n"
    "\t\t\t}\n"
    "\t\t}\n"
    "\t}\n"
    "}\n";

static void build_fake(const char *sys, const char *root)
{
    unsigned char *h;
    size_t         hlen;

    /* A GPT disk with an EFI partition and a LUKS2 partition. */
    put(sys, "sys/block/sda/size", "2097152\n");
    put(sys, "sys/block/sda/dev", "8:0\n");
    put(sys, "sys/block/sda/removable", "0\n");
    put(sys, "sys/block/sda/queue/logical_block_size", "512\n");
    put(sys, "sys/block/sda/queue/physical_block_size", "4096\n");
    put(sys, "sys/block/sda/queue/rotational", "1\n");
    put(sys, "sys/block/sda/device/model", "Sysfs Model   \n");
    put(sys, "sys/block/sda/sda1/partition", "1\n");
    put(sys, "sys/block/sda/sda1/start", "2048\n");
    put(sys, "sys/block/sda/sda1/size", "1048576\n");
    put(sys, "sys/block/sda/sda1/dev", "8:1\n");
    put(sys, "sys/block/sda/sda2/partition", "2\n");
    put(sys, "sys/block/sda/sda2/start", "1050624\n");
    put(sys, "sys/block/sda/sda2/size", "1044480\n");
    put(sys, "sys/block/sda/sda2/dev", "8:2\n");
    put(sys, "sys/block/sda/sda2/holders/dm-0", "");
    put(sys, "run/udev/data/b8:0", "S:disk/by-id/x\nE:ID_MODEL=Fake_Disk\nE:ID_SERIAL_SHORT=SN1\n"
                                   "E:ID_PART_TABLE_TYPE=gpt\nE:ID_PART_TABLE_UUID=disk-guid\n");
    put(sys, "run/udev/data/b8:1", "E:ID_PART_ENTRY_TYPE=c12a7328-f81f-11d2-ba4b-00a0c93ec93b\n"
                                   "E:ID_PART_ENTRY_UUID=part1-guid\n"
                                   "E:ID_PART_ENTRY_NAME=EFI\\x20System\\x5cx\n"
                                   "E:ID_FS_TYPE=vfat\nE:ID_FS_UUID=ABCD-1234\nE:ID_FS_USAGE=filesystem\n");
    put(sys, "run/udev/data/b8:2", "E:ID_PART_ENTRY_TYPE=0fc63daf-8483-4772-8e79-3d69d8477de4\n"
                                   "E:ID_FS_TYPE=crypto_LUKS\nE:ID_FS_VERSION=2\n"
                                   "E:ID_FS_UUID=11111111-2222-3333-4444-555555555555\n");
    h = luks2_header(&hlen);
    put(sys, "dev/", "");
    put_bytes(sys, "dev/sda2", h, hlen);
    free(h);

    /* A whole-disk LUKS1 device, no partition table. */
    put(sys, "sys/block/vdb/size", "4096\n");
    put(sys, "sys/block/vdb/dev", "253:16\n");
    put(sys, "run/udev/data/b253:16", "E:ID_FS_TYPE=crypto_LUKS\nE:ID_FS_VERSION=1\n");
    h = luks1_header();
    put_bytes(sys, "dev/vdb", h, 1024);
    free(h);

    /* A whole-disk LUKS device whose header cannot be read. */
    put(sys, "sys/block/vdc/size", "4096\n");
    put(sys, "sys/block/vdc/dev", "253:32\n");
    put(sys, "run/udev/data/b253:32", "E:ID_FS_TYPE=crypto_LUKS\n");

    /* Skipped: a loop device, an empty disk. */
    put(sys, "sys/block/loop0/size", "100\n");
    put(sys, "sys/block/sdz/size", "0\n");

    /* The LUKS mapping, and an md array. */
    put(sys, "sys/block/dm-0/size", "1040000\n");
    put(sys, "sys/block/dm-0/dev", "252:0\n");
    put(sys, "sys/block/dm-0/dm/name", "sda2_crypt\n");
    put(sys, "sys/block/dm-0/dm/uuid", "CRYPT-LUKS2-11111111222233334444555555555555-sda2_crypt\n");
    put(sys, "sys/block/dm-0/slaves/sda2", "");
    put(sys, "run/udev/data/b252:0", "E:ID_FS_TYPE=ext4\nE:ID_FS_UUID=root-fs-uuid\nE:ID_FS_LABEL=root\n");
    put(sys, "sys/block/dm-1/dm/name", "vg0-root\n");
    put(sys, "sys/block/dm-1/dm/uuid", "LVM-abcdef\n");
    put(sys, "sys/block/dm-2/dm/name", "plain\n");
    put(sys, "sys/block/dm-2/dm/uuid", "CRYPT-PLAIN-x\n");
    put(sys, "sys/block/dm-3/dm/name", "other\n");
    put(sys, "sys/block/md0/size", "100000\n");
    put(sys, "sys/block/md0/dev", "9:0\n");
    put(sys, "sys/block/md0/md/chunk_size", "524288\n");
    put(sys, "sys/block/md0/slaves/sdb1", "");
    put(sys, "sys/block/md0/slaves/sdc1", "");
    put(sys, "run/udev/data/b9:0", "E:MD_LEVEL=raid1\nE:MD_DEVICES=2\nE:MD_METADATA=1.2\n"
                                   "E:MD_UUID=md-uuid\nE:ID_FS_TYPE=xfs\n");

    /* Hardware, firmware, /proc. */
    put(sys, "sys/class/dmi/id/sys_vendor", "Example Corp\n");
    put(sys, "sys/class/dmi/id/product_name", "Model 1\n");
    put(sys, "sys/class/net/eth0/device/", "");
    put(sys, "sys/class/net/eth0/address", "52:54:00:12:34:56\n");
    put(sys, "sys/class/net/lo/address", "00:00:00:00:00:00\n");
    put(sys, "sys/firmware/efi/efivars/", "");
    put_bytes(sys, "sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c",
              (const unsigned char *)"\x06\x00\x00\x00\x01", 5);
    put(sys, "proc/cpuinfo", "processor\t: 0\nmodel name\t: Fake CPU @ 3GHz\nprocessor\t: 1\n"
                             "model name\t: Fake CPU @ 3GHz\n");
    put(sys, "proc/meminfo", "MemTotal:        2048 kB\nMemFree: 1 kB\n");
    put(sys, "proc/swaps", "Filename\tType\tSize\tUsed\tPriority\n/swap\\040file file 1024 0 -2\n");
    put(sys, "proc/sys/kernel/osrelease", "6.8.0-fake\n");
    put(sys, "proc/self/mountinfo",
        "22 1 0:21 / /proc rw - proc proc rw\n"
        "30 1 252:0 / / rw,relatime shared:1 - ext4 /dev/mapper/sda2_crypt rw\n"
        "31 30 8:1 / /boot/efi\\040x rw - vfat /dev/sda1 rw\n"
        "short line\n");

    /* The installed system's /etc and friends. */
    put(root, "etc/os-release", "NAME=\"Ubuntu\"\nID=ubuntu\nVERSION_ID=\"26.04\"\n"
                                "VERSION_CODENAME=resolute\nPRETTY_NAME='Ubuntu 26.04 LTS'\nBOGUS\n");
    put(root, "etc/hostname", "  web01  \n");
    put(root, "etc/fstab", "# a comment\nUUID=root-fs-uuid / ext4 errors=remount-ro 0 1\n"
                           "UUID=ABCD-1234 /boot/efi\\040x vfat umask=0077 0 1\n\nlonely\n");
    put(root, "etc/crypttab", "sda2_crypt UUID=11111111-2222-3333-4444-555555555555 none luks\n");
    put(root, "etc/lvm/backup/vg0", lvm_metadata);
    put(root, "etc/lvm/backup/broken", "vg {\n  id = \n");
    put(root, "var/log/installer/media-info", "Ubuntu-Server 26.04 LTS - Release amd64\n");
    put(root, "boot/grub/grub.cfg", "set default=0\n");
    put(root, "boot/efi/loader/loader.conf", "default ubuntu\n");
    put(root, "boot/efi/EFI/ubuntu/", "");
    put(root, "boot/efi/EFI/BOOT/", "");
    put(root, "var/lib/dpkg/status",
        "Package: ubuntu-desktop\nStatus: deinstall ok config-files\nVersion: 1\n\n"
        "Package: ubuntu-server\nStatus: install ok installed\nVersion: 1\n\n"
        "Package: ubuntu-server-minimal\nVersion: 1\nStatus: install ok installed\n");
}

static const struct rs_jval *at(const struct rs_jval *arr, size_t i)
{
    return (arr && arr->type == RS_JARRAY && i < arr->n) ? &arr->items[i] : NULL;
}

static uint64_t num(const struct rs_jval *obj, const char *key)
{
    uint64_t v = 0;

    (void)rs_jval_u64(rs_jobject_get(obj, key), &v);
    return v;
}

static bool notes_contain(const struct rs_jval *m, const char *needle)
{
    const struct rs_jval *notes = rs_jobject_get(m, "notes");
    size_t                i;

    for (i = 0; notes && i < notes->n; i++)
    {
        if (strstr(notes->items[i].s, needle))
        {
            return true;
        }
    }
    return false;
}

void test_machine(void)
{
    char                 *dir = rs_test_tmpdir();
    char                 *sys = rs_xasprintf("%s/sys", dir);
    char                 *root = rs_xasprintf("%s/root", dir);
    struct rs_jval        m;
    const struct rs_jval *v;
    const struct rs_jval *disk;
    const struct rs_jval *part;

    (void)mkdir(sys, 0755);
    (void)mkdir(root, 0755);
    build_fake(sys, root);
    memset(&m, 0, sizeof(m));
    rs_machine_describe(sys, root, &m);

    TEST_CASE("machine: system identity");
    v = rs_jobject_get(&m, "system");
    CHECK_STR(rs_jobject_str(v, "id"), "ubuntu");
    CHECK_STR(rs_jobject_str(v, "version_id"), "26.04");
    CHECK_STR(rs_jobject_str(v, "version_codename"), "resolute");
    CHECK_STR(rs_jobject_str(v, "pretty_name"), "Ubuntu 26.04 LTS");
    CHECK_STR(rs_jobject_str(v, "hostname"), "web01");
    CHECK_STR(rs_jobject_str(v, "kernel"), "6.8.0-fake");
    CHECK_STR(rs_jobject_str(v, "install_media"), "Ubuntu-Server 26.04 LTS - Release amd64");
    CHECK(rs_jobject_str(v, "architecture") != NULL);
    CHECK_STR(rs_jobject_str(v, "type"), "server");
    CHECK_CONTAINS(rs_jobject_str(v, "type_evidence"), "ubuntu-server package is installed");
    CHECK(strstr(rs_jobject_str(v, "type_evidence"), "ubuntu-desktop ") == NULL);
    CHECK_STR(rs_jobject_str(v, "virtualization"), "none");
    CHECK(rs_jobject_get(v, "container") == NULL);

    TEST_CASE("machine: hardware and firmware");
    v = rs_jobject_get(&m, "hardware");
    CHECK_STR(rs_jobject_str(v, "sys_vendor"), "Example Corp");
    CHECK_STR(rs_jobject_str(v, "cpu"), "Fake CPU @ 3GHz");
    CHECK_INT(num(v, "cpus"), 2);
    CHECK_INT(num(v, "memory"), 2048 * 1024);
    CHECK_INT(rs_jobject_get(v, "network")->n, 1);
    CHECK_STR(rs_jobject_str(at(rs_jobject_get(v, "network"), 0), "mac"), "52:54:00:12:34:56");
    v = rs_jobject_get(&m, "firmware");
    CHECK_STR(rs_jobject_str(v, "mode"), "uefi");
    CHECK(rs_jobject_get(v, "secure_boot") && rs_jobject_get(v, "secure_boot")->b);
    CHECK_INT(rs_jobject_get(v, "boot_loaders")->n, 2);
    CHECK_INT(rs_jobject_get(v, "efi_directories")->n, 2);

    TEST_CASE("machine: disks, partitions and what is on them");
    v = rs_jobject_get(&m, "disks");
    CHECK_INT(v->n, 3);   /* sda, vdb, vdc: not loop0, not the empty sdz */
    disk = at(v, 0);
    CHECK_STR(rs_jobject_str(disk, "name"), "sda");
    CHECK_INT(num(disk, "size"), 2097152ULL * 512);
    CHECK_INT(num(disk, "physical_block_size"), 4096);
    CHECK(rs_jobject_get(disk, "rotational")->b);
    CHECK_STR(rs_jobject_str(disk, "model"), "Fake_Disk");
    CHECK_STR(rs_jobject_str(disk, "serial"), "SN1");
    CHECK_STR(rs_jobject_str(rs_jobject_get(disk, "table"), "type"), "gpt");
    CHECK_STR(rs_jobject_str(rs_jobject_get(disk, "table"), "uuid"), "disk-guid");
    part = at(rs_jobject_get(disk, "partitions"), 0);
    CHECK_INT(num(part, "number"), 1);
    CHECK_INT(num(part, "start"), 2048 * 512);
    CHECK_INT(num(part, "size"), 1048576ULL * 512);
    CHECK_STR(rs_jobject_str(part, "label"), "EFI System\\x");
    CHECK_STR(rs_jobject_str(rs_jobject_get(part, "content"), "uuid"), "ABCD-1234");
    part = at(rs_jobject_get(disk, "partitions"), 1);
    CHECK_STR(rs_jobject_str(rs_jobject_get(part, "content"), "type"), "crypto_LUKS");
    CHECK_STR(rs_jobject_str(rs_jobject_get(part, "luks"), "cipher"), "aes-xts-plain64");
    CHECK_INT(num(rs_jobject_get(part, "luks"), "key_size"), 512);
    CHECK_INT(num(rs_jobject_get(part, "luks"), "sector_size"), 4096);
    CHECK_STR(rs_jobject_str(rs_jobject_get(part, "luks"), "pbkdf"), "argon2id");
    CHECK_STR(rs_jobject_str(rs_jobject_get(part, "luks"), "label"), "rootfs");
    CHECK_INT(rs_jobject_get(rs_jobject_get(part, "luks"), "tokens")->n, 2);
    CHECK_STR(rs_jobject_get(rs_jobject_get(part, "luks"), "tokens")->items[0].s, "systemd-tpm2");
    CHECK_STR(rs_jobject_get(rs_jobject_get(part, "luks"), "tokens")->items[1].s, "unknown");
    CHECK(at(rs_jobject_get(part, "holders"), 0) != NULL);
    CHECK_STR(at(rs_jobject_get(part, "holders"), 0)->s, "dm-0");
    disk = at(v, 1);
    CHECK_STR(rs_jobject_str(disk, "name"), "vdb");
    CHECK_STR(rs_jobject_str(rs_jobject_get(disk, "luks"), "cipher"), "aes-cbc-essiv:sha256");
    CHECK_INT(num(rs_jobject_get(disk, "luks"), "key_size"), 256);
    CHECK_STR(rs_jobject_str(rs_jobject_get(disk, "luks"), "hash"), "sha1");
    CHECK(notes_contain(&m, "vdc: the LUKS header could not be read"));

    TEST_CASE("machine: device mapper and RAID");
    v = rs_jobject_get(&m, "mapped");
    CHECK_INT(v->n, 4);
    CHECK_STR(rs_jobject_str(at(v, 0), "name"), "sda2_crypt");
    CHECK_STR(rs_jobject_str(at(v, 0), "kind"), "luks");
    CHECK_STR(rs_jobject_str(rs_jobject_get(at(v, 0), "content"), "label"), "root");
    CHECK_STR(rs_jobject_str(at(v, 1), "kind"), "lvm");
    CHECK_STR(rs_jobject_str(at(v, 2), "kind"), "crypt");
    CHECK_STR(rs_jobject_str(at(v, 3), "kind"), "other");
    v = rs_jobject_get(&m, "raid");
    CHECK_INT(v->n, 1);
    CHECK_STR(rs_jobject_str(at(v, 0), "level"), "raid1");
    CHECK_INT(num(at(v, 0), "chunk_size"), 524288);
    CHECK_INT(rs_jobject_get(at(v, 0), "devices")->n, 2);

    TEST_CASE("machine: LVM, mounts, fstab, crypttab, swap");
    v = rs_jobject_get(&m, "lvm");
    CHECK_INT(v->n, 1);
    CHECK_STR(rs_jobject_str(at(v, 0), "name"), "vg0");
    CHECK_CONTAINS(rs_jobject_str(at(v, 0), "metadata"), "extent_size = 8192");
    CHECK(notes_contain(&m, "/etc/lvm/backup/broken: not LVM metadata"));
    v = rs_jobject_get(&m, "mounts");
    CHECK_INT(v->n, 2);
    CHECK_STR(rs_jobject_str(at(v, 1), "mountpoint"), "/boot/efi x");
    CHECK_STR(rs_jobject_str(at(v, 0), "source"), "/dev/mapper/sda2_crypt");
    /* "/" exists on the machine running the test, so it can be measured;
     * "/boot/efi x" does not, and is left unmeasured rather than guessed. */
    CHECK(num(at(v, 0), "size") > 0);
    CHECK(rs_jobject_get(at(v, 1), "size") == NULL);
    v = rs_jobject_get(&m, "fstab");
    CHECK_INT(v->n, 2);
    CHECK_STR(rs_jobject_str(at(v, 1), "file"), "/boot/efi x");
    CHECK_STR(rs_jobject_str(at(v, 0), "passno"), "1");
    v = rs_jobject_get(&m, "crypttab");
    CHECK_STR(rs_jobject_str(at(v, 0), "keyfile"), "none");
    v = rs_jobject_get(&m, "swap");
    CHECK_STR(rs_jobject_str(at(v, 0), "file"), "/swap file");
    CHECK_INT(num(at(v, 0), "size"), 1024 * 1024);

    TEST_CASE("machine: the description goes through the index and back");
    {
        struct rs_index ix;
        struct rs_index back;
        char           *path = rs_xasprintf("%s/ix.json", dir);
        FILE           *fp = fopen(path, "w");
        struct rs_buf   err;

        rs_index_init(&ix);
        rs_jval_copy(&ix.machine, &m);
        CHECK(fp != NULL);
        if (fp)
        {
            CHECK(rs_index_write(&ix, fp));
            (void)fclose(fp);
        }
        rs_index_init(&back);
        rs_buf_init(&err);
        CHECK(rs_index_parse(&back, "", 0, "x", &err) == false);
        rs_buf_reset(&err);
        {
            int     fd = open(path, O_RDONLY);
            char    buf[65536];
            size_t  n = 0;
            ssize_t r;

            while (fd >= 0 && (r = read(fd, buf + n, sizeof(buf) - 1 - n)) > 0)
            {
                n += (size_t)r;
            }
            if (fd >= 0)
            {
                (void)close(fd);
            }
            buf[n] = '\0';
            CHECK(rs_index_parse(&back, buf, n, "ix", &err));
        }
        CHECK_STR(rs_jobject_str(rs_jobject_get(&back.machine, "system"), "hostname"), "web01");
        CHECK_INT(rs_jobject_get(&back.machine, "disks")->n, 3);
        rs_index_free(&back);
        rs_buf_reset(&err);
        {
            const char *bad = "{\"format\": \"restate-index\", \"machine\": 5, \"entries\": []}";

            CHECK(!rs_index_parse(&back, bad, strlen(bad), "ix", &err));
        }
        CHECK_CONTAINS(err.data, "\"machine\" is not an object");
        rs_index_free(&back);
        rs_index_free(&ix);
        rs_buf_free(&err);
        free(path);
    }
    rs_jval_free(&m);

    TEST_CASE("machine: a system without /sys/block says so");
    {
        char *empty = rs_xasprintf("%s/empty", dir);

        (void)mkdir(empty, 0755);
        memset(&m, 0, sizeof(m));
        rs_machine_describe(empty, empty, &m);
        CHECK(notes_contain(&m, "only read on Linux"));
        CHECK(rs_jobject_get(&m, "disks") == NULL);
        rs_jval_free(&m);
        free(empty);
    }

    TEST_CASE("machine: desktop, virtual machines and containers");
    {
        static const char *const cases[][4] = {
            /* DMI field, its value, CPU flags, expected */
            { "sys_vendor", "QEMU", "", "kvm" },
            { "sys_vendor", "VMware, Inc.", "", "vmware" },
            { "product_name", "Virtual Machine", "", "hyperv" },
            { "sys_vendor", "innotek GmbH", "", "virtualbox" },
            { "product_name", "Google Compute Engine", "", "google" },
            { "sys_vendor", "Dell Inc.", "flags : fpu hypervisor sse", "unknown" },
            { "sys_vendor", "Dell Inc.", "flags : fpu sse", "none" },
        };
        size_t k;

        for (k = 0; k < sizeof(cases) / sizeof(cases[0]); k++)
        {
            char *one = rs_xasprintf("%s/virt%zu", dir, k);
            char *rel = rs_xasprintf("sys/class/dmi/id/%s", cases[k][0]);

            (void)mkdir(one, 0755);
            put(one, rel, cases[k][1]);
            put(one, "proc/cpuinfo", cases[k][2]);
            if (k == 0)
            {
                put(one, "usr/share/wayland-sessions/gnome.desktop", "[Desktop Entry]\n");
                put(one, ".dockerenv", "");
            }
            if (k == 1)
            {
                put(one, "usr/share/xsessions/xfce.desktop", "[Desktop Entry]\n");
                put(one, "run/.containerenv", "");
            }
            memset(&m, 0, sizeof(m));
            rs_machine_describe(one, one, &m);
            v = rs_jobject_get(&m, "system");
            rs_test_case = cases[k][3];
            CHECK_STR(rs_jobject_str(v, "virtualization"), cases[k][3]);
            CHECK_STR(rs_jobject_str(v, "type"), k < 2 ? "desktop" : "server");
            if (k == 0)
            {
                CHECK_STR(rs_jobject_str(v, "container"), "docker");
                CHECK_CONTAINS(rs_jobject_str(v, "type_evidence"), "gnome.desktop");
            }
            if (k == 1)
            {
                CHECK_STR(rs_jobject_str(v, "container"), "podman");
            }
            if (k == 2)
            {
                CHECK_STR(rs_jobject_str(v, "type_evidence"),
                          "no desktop package or graphical session is installed");
            }
            rs_jval_free(&m);
            free(rel);
            free(one);
        }
        {
            char *xen = rs_xasprintf("%s/xen", dir);

            (void)mkdir(xen, 0755);
            put(xen, "sys/hypervisor/type", "xen\n");
            memset(&m, 0, sizeof(m));
            rs_machine_describe(xen, xen, &m);
            CHECK_STR(rs_jobject_str(rs_jobject_get(&m, "system"), "virtualization"), "xen");
            rs_jval_free(&m);
            free(xen);
        }
    }

    TEST_CASE("machine: LVM metadata parsing");
    {
        struct rs_jval lvm;
        struct rs_buf  err;
        const char    *bad[][2] = {
            { "vg {\n", "unterminated section" },
            { "}", "unexpected '}'" },
            { "a = \"x", "unterminated string" },
            { "a = 99999999999999999999999", "number too large" },
            { "a = -", "bad number" },
            { "a = ", "expected a value" },
            { "a = [1, 2", "unterminated list" },
            { "a = [x]", "expected a value" },
            { "= 1", "expected a name" },
            { "a 1", "expected '=' or '{'" },
            { "a = @", "expected a value" },
            { "a = 1 a = 2", "appears twice" },
            { "a{b{c{d{e{f{g{h{i{j{k{l{m{n{o{p{q{r{}}}}}}}}}}}}}}}}}}", "nested too deeply" },
        };
        size_t         i;

        rs_buf_init(&err);
        memset(&lvm, 0, sizeof(lvm));
        CHECK(rs_lvm_parse(lvm_metadata, strlen(lvm_metadata), &lvm, &err));
        v = rs_jobject_get(&lvm, "vg0");
        CHECK_INT(num(v, "extent_size"), 8192);
        CHECK_INT(rs_jobject_get(v, "status")->n, 3);
        CHECK_STR(rs_jobject_str(rs_jobject_get(rs_jobject_get(v, "physical_volumes"), "pv0"),
                                 "device"), "/dev/mapper/sda2_crypt");
        CHECK(rs_jobject_get(rs_jobject_get(v, "logical_volumes"), "root-lv.1+x") != NULL);
        CHECK_STR(rs_jobject_str(&lvm, "description"), "Created *after* executing 'lvcreate'");
        rs_jval_free(&lvm);
        CHECK(rs_lvm_parse("a = -5 b = \"q\\\"uote\"", 20, &lvm, &err));
        CHECK(rs_jobject_get(&lvm, "a")->neg);
        rs_jval_free(&lvm);
        CHECK(rs_lvm_parse("a = \"x\0y\"", 9, &lvm, &err) == false);
        rs_jval_free(&lvm);
        for (i = 0; i < sizeof(bad) / sizeof(bad[0]); i++)
        {
            rs_test_case = bad[i][1];
            rs_buf_reset(&err);
            CHECK(!rs_lvm_parse(bad[i][0], strlen(bad[i][0]), &lvm, &err));
            CHECK_CONTAINS(err.data, bad[i][1]);
            rs_jval_free(&lvm);
        }
        rs_buf_free(&err);
    }

    TEST_CASE("machine: LUKS headers");
    {
        struct rs_jval luks;
        unsigned char *h;
        size_t         hlen;

        memset(&luks, 0, sizeof(luks));
        h = luks2_header(&hlen);
        CHECK(!rs_luks_parse(h, 100, &luks));
        CHECK(rs_luks_parse(h, 4096, &luks));   /* the binary header alone */
        CHECK(rs_jobject_get(&luks, "cipher") == NULL);
        CHECK_STR(rs_jobject_str(&luks, "uuid"), "11111111-2222-3333-4444-555555555555");
        rs_jval_free(&luks);
        memcpy(h + 4096, "{not json", 9);
        CHECK(rs_luks_parse(h, hlen, &luks));
        CHECK(rs_jobject_get(&luks, "cipher") == NULL);
        rs_jval_free(&luks);
        h[6] = 0;
        h[7] = 3;
        CHECK(rs_luks_parse(h, hlen, &luks));
        CHECK_INT(num(&luks, "version"), 3);
        rs_jval_free(&luks);
        h[0] = 'X';
        CHECK(!rs_luks_parse(h, hlen, &luks));
        rs_jval_free(&luks);
        free(h);
    }

    TEST_CASE("json: building and writing trees");
    {
        struct rs_jval t;
        struct rs_jval c;
        struct rs_buf  b;

        memset(&t, 0, sizeof(t));
        rs_jval_set_object(&t);
        rs_jobj_str(&t, "s", "x\xff");
        rs_jobj_str(&t, "absent", NULL);
        rs_jval_set_i64(rs_jobj_add(&t, "neg"), -7);
        rs_jval_set_i64(rs_jobj_add(&t, "min"), INT64_MIN);
        rs_jval_set_i64(rs_jobj_add(&t, "pos"), 7);
        rs_jobj_bool(&t, "b", false);
        rs_jval_set_array(rs_jobj_add(&t, "a"));
        rs_jobj_add(&t, "null");
        rs_buf_init(&b);
        rs_json_write(&b, &t, 0, 0);
        CHECK_STR(b.data, "{\"s\": \"x\xef\xbf\xbd\", \"neg\": -7, \"min\": -9223372036854775808, "
                          "\"pos\": 7, \"b\": false, \"a\": [], \"null\": null}");
        memset(&c, 0, sizeof(c));
        rs_jval_copy(&c, &t);
        rs_buf_reset(&b);
        rs_json_write(&b, &c, 2, 0);
        CHECK_CONTAINS(b.data, "\"neg\": -7");
        rs_jval_free(&c);
        rs_jval_free(&t);
        rs_buf_free(&b);
    }

    rs_test_rmtree(dir);
    free(sys);
    free(root);
    free(dir);
}
