#!/usr/bin/env bash
#
# Copyright (c) 2026 Bryan C. Everly
# SPDX-License-Identifier: BSD-2-Clause
#
# Generate man/restate.8 from the program's own --help output.
#
#   scripts/gen-man.sh BINARY OUTPUT        write the manpage
#   scripts/gen-man.sh --check BINARY PAGE  fail if the committed page is stale
#
# The commands, options, exit statuses and examples in the manpage are not
# maintained by hand: they are read out of `restate --help`, which is itself
# generated from src/commands.def and src/options.def. Adding an option updates
# the parser, the help, the manpage and the README together, and `make lint`
# runs the --check mode so a page that was not regenerated fails rather than
# documenting an option that no longer exists.
#
# Only the prose sections below are written here: the part a generator cannot
# invent, and short enough to keep correct by reading it.
#
# The date in the .TH line is the one thing --check ignores -- the date, not
# the line, which also names the version -- and a page whose content has not
# changed keeps the date it already has. A date taken from a
# file's mtime changes on every fresh checkout, and a freshness check that
# fails on a clean clone is a check people learn to ignore.
set -euo pipefail

CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
  shift
fi

BINARY="${1:?usage: gen-man.sh [--check] BINARY OUTPUT}"
OUTPUT="${2:?usage: gen-man.sh [--check] BINARY OUTPUT}"

[ -x "$BINARY" ] || { echo "gen-man.sh: $BINARY is not executable" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# The VERSION file, not --version: a working build reports "-dev", and the
# manpage is a committed file that names the release.
VERSION="$(cat "$REPO_ROOT/VERSION")"

# Today, unless the existing page carries a date already; see above.
DATE="$(date -u '+%B %d, %Y')"
DATE="${DATE/ 0/ }"
if [ -f "$OUTPUT" ]; then
  OLD_DATE="$(sed -n 's/^\.TH RESTATE 8 "\([^"]*\)".*/\1/p' "$OUTPUT" | head -1)"
  [ -n "$OLD_DATE" ] && KEEP_DATE="$OLD_DATE"
fi

# roff treats a leading '.' or '\'' as a request, and a bare '-' as a hyphen
# rather than the minus an option needs.
escape_roff() {
  sed -e 's/\\/\\e/g' -e 's/-/\\-/g' -e 's/^[.'"'"']/\\\&&/'
}

HELP="$("$BINARY" --help)"

# The lines of one section of --help, between its heading and the next blank
# line, with wrapped continuation lines joined back onto their entry.
section() {
  printf '%s\n' "$HELP" | awk -v want="$1" '
    $0 == want ":" { on = 1; next }
    on && /^$/     { exit }
    on {
      if ($0 ~ /^                    /) {     # a continuation line
        sub(/^ +/, "")
        # A term too long for its column has its description start on the
        # next line; keep the two-space gap that separates the two.
        entry = entry (entry ~ /[^ ]  +[^ ]/ ? " " : "  ") $0
        next
      }
      if (entry != "") print entry
      entry = $0
    }
    END { if (entry != "") print entry }
  '
}

# "  term   description" -> .TP entries. Terms are bold, with an argument after
# "=" or a space in italics.
entries() {
  local kind="$1"
  while IFS= read -r line; do
    local term desc
    term="$(printf '%s' "$line" | sed -E 's/^ +//; s/ {2,}.*$//')"
    desc="$(printf '%s' "$line" | sed -E 's/^ +[^ ].*[^ ] {2,}//; s/^ +//' | escape_roff)"
    if [ "$kind" = "option" ]; then
      term="$(printf '%s' "$term" | escape_roff \
              | sed -E 's/(\\-\\-[a-z-]+)=([A-Z]+)/\\fB\1\\fR=\\fI\2\\fR/; s/^(\\-[A-Za-z]),/\\fB\1\\fR,/; s/^(\\-\\-[a-z-]+)$/\\fB\1\\fR/')"
    else
      local name args
      name="${term%% *}"
      args=""
      [ "$name" != "$term" ] && args=" \\fI${term#* }\\fR"
      term="\\fB${name}\\fR${args}"
    fi
    printf '.TP\n%s\n%s\n' "$term" "$desc"
  done
}

TMP="$(mktemp)"
trap 'rm -f "$TMP" "$TMP.a" "$TMP.b"' EXIT

{
  cat <<HEADER
.\" Generated by scripts/gen-man.sh from \`restate --help\` -- do not edit by hand.
.\" Run \`make man\` after changing src/options.def or src/commands.def.
.\"
.\" Copyright (c) 2026 Bryan C. Everly
.\" SPDX-License-Identifier: BSD-2-Clause
.TH RESTATE 8 "${KEEP_DATE:-$DATE}" "restate $VERSION" "System Manager's Manual"
.nh
.SH NAME
restate \- back up what a fresh OS install would not put back, to rebuild the machine
.SH SYNOPSIS
.B restate
.RI [ option ...]
.I command
.RI [ argument ...]
.SH DESCRIPTION
.B restate
records what makes this machine different from a fresh install of its
operating system, so that after the disk is wiped and the system reinstalled,
the difference can be put back.
.PP
A full backup copies every file. Most of those files came from the operating
system or its packages and can be fetched again; what cannot be fetched again
is the configuration, the data and the local changes. That difference is
usually a small fraction of the disk, and it is what
.B restate
records.
.PP
Every path is given a class by a list of rules (see
.BR CLASSES " and " RULES
below), and
.B capture
walks the tree writing an
.IR image :
a gzip'd tar holding an
.I index
of every recorded path and the content of everything worth keeping (see
.BR "IMAGES AND INDEXES" ).
.B scan
writes the index alone. Two images or indexes can be compared with
.BR diff ,
and either compared against the tree as it is now with
.BR verify .
.PP
The walk never follows a symbolic link, never opens a path longer than one
component, and checks every directory and file it opens against what it was
told it would find, so that a tree being changed underneath it cannot steer it
somewhere else.
.SH COMMANDS
Options may appear before or after the command.
HEADER

  section "Commands" | entries command

  printf '.SH OPTIONS\n'
  section "Options" | entries option

  cat <<'CLASSES'
.SH CLASSES
.TP
.B ephemeral
Runtime state with no meaning after a reboot:
.IR /proc ,
.IR /run ,
.IR /tmp ,
process ID files and sockets. Never recorded, and never descended into.
.TP
.B expendable
Could be kept, but a rebuilt machine does not need it, because it can be
fetched or rebuilt from something else: caches, downloads, dependencies,
installed toolchains, logs; see
.BR "WHAT IS LEFT OUT" .
Not recorded unless
.B \-\-all
is given, or a rule makes it state.
.TP
.B baseline
Supplied by the operating system or its packages:
.IR /usr ,
the package database, the kernel. Recorded with content digests, so that a
comparison against what the vendor shipped can tell which of these files were
changed locally.
.TP
.B state
What makes this machine this machine:
.IR /etc ,
.IR /home ,
.IR /root ,
.IR /var/lib ,
.IR /usr/local .
Always recorded. A path that no rule covers is state: a file nobody meant to
keep costs some space, a file nobody meant to lose costs the restore.
.SH RULES
A rule is a class and a pattern, one per line:
.PP
.RS
.nf
state       /srv
expendable  /srv/cache    # comments start with a '#' after a space
ephemeral   *.sock
.fi
.RE
.PP
The
.B last
rule that covers a path decides its class, as in
.BR gitignore (5),
so a site rules file given with
.B \-\-rules
overrides any built-in rule. A rule covers the path it names and everything
beneath it. Because an ephemeral or expendable directory is not descended
into, no later rule can rescue something inside one; classify the directory as
state and its unwanted children as expendable instead.
.PP
In a pattern,
.B *
matches any run of characters except
.BR / ,
.B **
matches any run including
.BR / ,
.B **/
matches zero or more whole directories,
.B ?
matches one character except
.BR / ,
and a backslash makes the next character literal. A pattern that does not
begin with
.B /
matches at any depth.
.PP
The built-in rules are chosen by operating system: linux, freebsd, openbsd,
netbsd and darwin.
.B restate rules
prints them in this format, with the reason for each, so that a site that
disagrees can save them, edit them, and run with
.BR "\-N \-R" " file" .
.SH WHAT IS LEFT OUT
By default an image holds what cannot be had again any other way. Anything
that can be downloaded again, or rebuilt from files the image does keep, is
expendable, so it costs neither time nor space in a capture:
.TP
.B Downloads
.I ~/Downloads
in every user's home, wherever homes are kept
.RI ( /home ,
.I /usr/home
on FreeBSD,
.I /Users
on macOS, and root's).
.TP
.B Caches and the trash
.IR ~/.cache ,
the desktop's trash and the trash on other drives, thumbnails, the caches
Chrome, Chromium, Brave, Edge and Electron apps keep inside their profiles
(service-worker, compiled-code and GPU shader caches \- not bookmarks,
logins or site data),
.IR /var/cache ,
SonarScanner's cache, and on macOS the per-user and sandboxed apps' caches.
.TP
.B Dependencies
Anything a lock file or a manifest installs again:
.IR node_modules ,
npm, Yarn, pnpm and Bun caches, Python virtual environments
.RI ( .venv ,
.IR venv ,
.IR ~/.venvs ,
pipenv's), Gradle, Maven, Ivy, Cargo, Go, NuGet, Dart, Haskell and conda
caches, installed Ruby gems, Terraform providers.
.TP
.B Build output
Compiled Python, object files, CMake's build files, Next.js, Nuxt, Parcel,
Turborepo and Zig caches, ccache, and Xcode's DerivedData.
.TP
.B Installed toolchains and apps
What a version manager or store installs again: nvm, pyenv, rbenv, asdf,
mise, Volta, SDKMAN!, ghcup, elan and rustup toolchains; Julia packages; VS
Code extensions and its remote server; the Android SDK, PlatformIO, Arduino
and JetBrains Toolbox installs; Steam games; Flatpak apps and runtimes
(their remotes and overrides are kept); snaps; Ollama models.
.TP
.B Images
Container images and layers (containerd, Docker, Podman \- not their
volumes, which are data), LXD's image cache, installer images libvirt boots
from, the snaps the installer seeded, and installer and disc images
.RI ( *.iso ),
cloud images and downloads that never finished
.RI ( *.part ,
.IR *.crdownload ). Virtual machines' own disks and
definitions are data, and are kept; a suspended VM's saved memory is not,
and without it the VM boots afresh.
.TP
.B Never at all
Swap files, process IDs and sockets, per-filesystem
.IR lost+found ,
the last X session's error log; and
.IR /proc ,
.IR /sys ,
.IR /run ,
.IR /tmp ,
.IR /mnt ,
.I /media
and the like.
.PP
None of it is lost for good by being left out: it is kept with
.BR \-\-all ,
or one piece at a time with a rule in a rules file, since a site's rules
come after the built-in ones and the last match wins:
.PP
.RS
.nf
state  /home/alice/Downloads        # keep one user's downloads
state  /srv/app/node_modules        # an app deployed with its dependencies
state  **/.venv                     # every virtual environment
.fi
.RE
.PP
.B restate classify
says which rule decided a path, and
.B restate rules
lists every rule with its reason.
.SH MACHINE
An index of the running system's own root \- a
.B capture
or
.B scan
of
.I /
\- also describes the machine underneath the files, in a
.B """machine"""
object, so that it can be rebuilt before the files are put back.
.B restate machine
prints the same description on its own.
.PP
It records the operating system (from
.IR os\-release ),
the kernel, the architecture, the host name and the media the machine was
first installed from; whether it is a desktop or a server, with the evidence
for that \- desktop metapackages, graphical sessions installed \- since the
installer chosen for a rebuild depends on it; whether it is bare metal or a
virtual machine, and on what, and whether it is a container; the hardware (from DMI: vendor, product, firmware
version), the processor, the memory and the physical network interfaces with
their addresses; UEFI or BIOS, the Secure Boot state, and the boot loaders
installed; every disk, with its size, sector sizes, model and serial number;
its partition table (GPT or MBR) and, for each partition, its offset, size,
type, UUID, name and flags, and what is on it \- a filesystem with its type,
UUID and label, LUKS, an LVM physical volume, a RAID member; the
device-mapper devices built on them; each LVM volume group's own metadata, as
.I /etc/lvm/backup
holds it; software RAID arrays; the persistent filesystems mounted, with their size and the space used on
each \- what a replacement disk, or a virtual one, actually has to hold \- and
.IR /etc/fstab ,
.I /etc/crypttab
and the swap in use.
.PP
All of it is read from files \- sysfs, the udev database,
.IR /proc ,
.I /etc
\- except a LUKS volume's cipher, key size and key-derivation function, which
are in the volume's header and need root to read, as are its LUKS2 tokens:
a
.B systemd\-tpm2
or
.B clevis
token means the volume unlocks with this machine's TPM or a network server,
and will not unlock that way on any other machine. No key, passphrase or key
slot is ever recorded. Anything that could not be read is listed in the
description's
.B """notes"""
rather than guessed.
.PP
On the BSDs the kernel is asked instead, each in its own terms: on FreeBSD,
GEOM's configuration
.RB ( "sysctl kern.geom.conftxt" :
disks, GPT and MBR partitions, GELI providers) and the boot method; on
OpenBSD, each disk's disklabel; on NetBSD, the wedges of a GPT disk or the
disklabel of any other \- the last two need root, as reading a disklabel
does. The hardware comes from
.BR sysctl (3),
the interfaces from
.BR getifaddrs (3)
and the mounts from
.BR getmntinfo (3).
On macOS, whose disks are described through Disk Arbitration rather than
libc, the description holds the system, hardware, interfaces and mounts, and
a note saying so.
.B buildsheet
and
.B autoinstall
are written for Linux in this version.
.PP
An index of any other tree \- a disk mounted from another machine, a
directory \- has no machine description, because the disks it would describe
are this machine's, not that tree's.
.SH PACKAGES
A reinstall puts back the distribution's own packages; everything installed
since \- by apt from the archive, a PPA or a vendor's repository, by snap or
flatpak, by pip, npm or cargo \- has to be installed again, and the rules
leave it out of an image, because a package manager puts it back. So every
.B capture
and
.B scan
records what is installed, and where it came from, in a
.B """packages"""
object.
.B restate packages
prints the same inventory on its own, of this tree or of the one an image
was taken from. All of it is read from the package managers' own files,
never by running them, so the inventory of a tree mounted from another disk
is that tree's.
.PP
For apt it records every package dpkg has unpacked, with its version and
architecture; whether it was installed by hand or as a dependency (from
.IR /var/lib/apt/extended_states );
whether it is held; and how far dpkg got with one it did not finish. It
records every repository in
.I /etc/apt/sources.list
and
.IR /etc/apt/sources.list.d ,
in either format, with the key each is signed with, and every key file apt
trusts \- whole, wherever it is, because a key under
.I /usr/share/keyrings
is not kept in an image, and apt refuses a repository whose key is missing.
Only public keys are there to record. From apt's package lists it records
which repositories each installed version can be had from again, and, for
the ones none can, why:
.B """superseded"""
where a repository has another version of the package now, and
.B """local"""
where none has it at all \- it was installed from a
.I .deb
file, and only that file puts it back. The lists are as fresh as the last
.BR "apt update" .
.PP
For snap it records each snap's revision, channel and confinement, from
snapd's state, which only root can read; otherwise the revisions alone, from
.IR /snap ,
and a note. A snap installed from a file rather than the store is marked
.BR """local""" .
For flatpak it records the remotes and the apps of each installation, the
system's and each user's. For pip, npm, cargo, pipx and Ruby gems it records
what was installed outside any project: system-wide, and in the home
directory of root and of each user who logs in. On OpenBSD and NetBSD it
records the installed packages. It records the alternatives chosen by hand
.RB ( "update-alternatives \-\-set" ),
and what each points at; the rest follow the packages by themselves.
Other package managers \- rpm, pacman, apk,
Nix, Guix, Homebrew, conda, FreeBSD's
.BR pkg ,
macOS receipts \- are listed in
.B """managers"""
as present, with no inventory in this version, so that an image says what it
is missing rather than leaving it out silently.
.PP
With
.BR \-\-keep\-local\-packages ,
a capture also keeps the files that put back what no repository or store
can: the
.I .deb
of each installed version no repository has, from apt's cache
.RI ( /var/cache/apt/archives ),
and the
.I .snap
of each snap installed from a file, from snapd's
.RI ( /var/lib/snapd/snaps ),
in the image's kit as well as its files. Both caches are left out of an image
otherwise. A package installed from a downloaded file is often not in apt's
cache; the capture warns of each one it cannot keep, and
.B dpkg\-repack
.I NAME
run in
.I /var/cache/apt/archives
rebuilds one from what is installed, under the name the next capture looks
for. Where that will not do \- dpkg\-repack refuses a package whose own
maintainer scripts have the wrong permissions \-
.BI \-\-deb " NAME" = FILE
names the
.I .deb
to keep for package
.IR NAME ,
wherever it is; it has to be a
.I .deb
file, and
.I NAME
a package no repository has. A superseded version, one a repository has a
newer version of, is kept if it is in the cache and passed over quietly if
not, since a rebuild installs the newer one.
.B verify
walks the files an image kept, so they are not reported as deleted. Off by
default: those files can be large.
.SH BASELINE
.I Baseline
means
.I supplied by the operating system or its packages
\- the files a reinstall puts back on its own. In this version that is
decided by the rules alone, from where a file lives:
.IR /usr ,
.IR /bin ,
.IR /sbin ,
.IR /lib ,
.IR /boot ,
the package database, and the equivalents on each system, as
.B restate rules
lists them.
.PP
The baseline is not read from an installation image, and does not depend on
whether a machine was installed as a desktop or a server, or for which
processor: it is decided on the machine in front of it, so whatever was
installed there is what it sees. (The installer still matters for putting a
machine back, and
.B restate installer
names and fetches it; see
.BR INSTALLERS .)
A baseline file is recorded in the index with
its owner, mode, times and SHA-256, and its content is left out of an image
unless
.B \-\-baseline\-content
is given.
.PP
What this version does not yet do is check those digests against what the
vendor shipped, so a baseline file changed by hand \- an edited file under
.IR /usr/share ,
a replaced binary \- is recorded but not kept. Every system restate supports
already holds the vendor's digests for every installed file in its own package
database, and a later version reads them; see
.BR BUGS .
Until then, keep anything changed under a baseline path with
.BR \-\-baseline\-content ,
or classify it as state in a rules file.
.SH INSTALLERS
.B restate installer
names the installation image a machine is rebuilt from, worked out from its
machine description: the distribution and release, the point release, the
architecture, and whether it is a desktop or a server, with the evidence for
that. Given an image, index or saved description, it names the installer for
the machine that was captured rather than this one. Ubuntu is supported in
this version: the desktop image for a desktop on amd64 or arm64, and the
server image otherwise, from
.I releases.ubuntu.com
(and
.I old\-releases.ubuntu.com
once a release reaches end of life) for amd64, and
.I cdimage.ubuntu.com
for other architectures.
.PP
.B restate installer fetch
downloads it. The vendor's
.I SHA256SUMS
and its signature are fetched first and checked with
.BR gpgv (1)
against the vendor's signing key, which is built into
.B restate
and pinned by fingerprint: a signature counts only when gpgv names that
fingerprint, not merely when it succeeds. The image listed for the machine's
own point release is chosen, or else the newest listed. It is downloaded with
.BR curl (1)
over HTTPS only, resuming an interrupted download, and checked against the
signed checksum; only then is it moved into place, and its path printed. An
image already in the cache that matches is not downloaded again.
.B \-\-cache
changes where images are kept, and
.B \-\-mirror
fetches from another https:// or file:// directory holding the same files \-
which are checked against the same key.
.SH PROGRESS
A capture of a whole machine can read hundreds of gigabytes and take an
hour, and by default says nothing until it is done.
.B \-\-progress
shows how far it has got:
.PP
.RS
.nf
restate: counting  812345 paths  184 GiB to read  0:00:41
restate: walking [#######.............]  35%  64 GiB of 184 GiB  91 MiB/s  0:22:30 left
  .../home/alice/dev/project/src/main.c
restate: writing [##############......]  70%  129 GiB of 184 GiB  305 MiB/s  0:03:01 left
.fi
.RE
.PP
A walk that reads files
.RB ( scan ,
.BR capture ,
.BR verify )
first counts them \- metadata only, no file is read, so this is quick \- to
know how many bytes the walk will read. The walk then shows a bar, a
percentage, how much has been read of how much, the throughput, the time
left at that rate, and under the bar the path being read. Writing an image,
the last step of a capture, shows the same against the content to be
written. Downloading an installer shows curl's own progress bar.
.PP
On a terminal the two lines are redrawn in place a few times a second, the
bar as wide as the terminal allows. They are drawn on the terminal even
when standard error is redirected \- to a log, through
.BR tee (1)
\- and each phase's final line is also written to standard error, so the
log records how each went. With no terminal at all, as under
.BR cron (8),
a line is written to standard error every ten seconds instead. It is off
unless asked for, and
.B \-\-quiet
does not turn it off: one option asks for silence about everything else,
the other for this.
.SH REBUILDING
.B restate buildsheet
writes a plain-text runbook for rebuilding the machine onto a blank disk:
the hardware and firmware it needs, the installer, the disk layout as it
was, and the commands that recreate it \-
.BR sfdisk (8)
for the partition tables,
.BR cryptsetup (8)
for LUKS,
.BR mdadm (8)
for RAID,
.BR pvcreate (8)
and
.BR vgcfgrestore (8)
for LVM (the volume group's own metadata backup, so every volume comes back
at its old extents), and
.BR mkfs (8)
and
.BR mkswap (8)
for the filesystems \- with the original UUIDs, so the restored
.I /etc/fstab
and
.I /etc/crypttab
still name the right volumes. Then how to point the installer at that
layout, what to do after it, how to install the packages again, and how to
put the files back. Nothing is run:
every command is printed for a person to check against
.BR lsblk (8)
and run.
.PP
The packages come from the image's inventory (see
.BR PACKAGES ),
and go back before the files, because a restored configuration file where a
package puts its own, or one naming a program not yet installed, makes
packages fail to install: first
.I /etc/apt
from the image and the repository keys kept outside it, written back from
the inventory with
.BR base64 (1);
then every package installed by hand, pinned to the version that was
installed, so it comes from the repository it came from and not another
that has the same name \- except the boot loader and the kernel, which the
installer chose for the machine it installed onto. They are installed by a
script that looks each one up first, because one that cannot be had \- a
vendor that keeps only its newest version, a repository whose key has
expired \- would otherwise stop a single
.B apt\-get install
of them all and install none: the version recorded where a repository still
has it, the current one where not, and a word about any none has; those
found together, or one at a time if apt refuses them together. Then the held
ones held again;
the ones the image keeps, installed from it; the ones no repository has any
more, or ever had, listed with what to do about them; then the snaps by
channel, the flatpak apps by remote, what pip, npm, pipx, cargo and gem
installed, each by its owner, and the alternatives chosen by hand. Every name and version in those commands is
quoted where it needs to be, because the inventory says whatever the
captured tree said. The restore that follows puts the old configuration
back over the packages' own.
.PP
Partitions that belong to another operating system \- Windows, BitLocker,
macOS, a VeraCrypt container \- are never formatted. Rebuilding the same
machine, the sheet offers two paths: a blank disk, where they are recreated
empty for that system's own restore, or the same disk, where the partition
table and the EFI system partition they boot from are left alone.
.PP
.B restate autoinstall
writes the same layout as an Ubuntu autoinstall file, for an install nobody
has to attend: storage in curtin's terms, locale, keyboard, time zone, host
name, network and the SSH server. A LUKS passphrase has to be in the file
for the installer to format the volume, and is left as CHANGE-ME, as is the
first account's password, which the restore replaces. The snaps are
installed at the new system's first boot, by a service the file leaves
behind
.RB ( restate\-firstboot ,
which removes itself; what it says is in its journal): the desktop
installer ignores an autoinstall file's
.B snaps
section, and snapd does not run while the system is being installed. Given
.B \-\-image\-at
.IR PATH ,
where the installer will find the image (a disk or share mounted there), its
late-commands do the rest of what the build sheet does, unattended and in
the same order: the packages, then the image's files over them \- keeping
the installer's
.I /etc/fstab
and
.IR /etc/crypttab ,
since it formatted the volumes \- and the initramfs and boot loader rebuilt.
A package that will not install is said in the installer's log and the
restore goes on; an image that is not there stops the install, saying so.
What only a person can do \- per-user installations, a package from a file
the image does not keep \- is listed in the file, for after the first boot.
.PP
With
.BR "\-\-target vm" ,
either one rebuilds the machine as a virtual machine: the Linux volumes only, each
filesystem sized to what it uses plus room to grow, disks named
.IR /dev/vda ,
and a
.BR virt-install (1)
command that gives the VM a modest share of a host \- at most 8 GiB of
memory and 4 CPUs, and never more than the original had, since a test
rebuild often runs on the very machine it came from; the hardware-only
packages (microcode, firmware and sensor tools, GPU drivers) are removed
and
.B qemu-guest-agent
added.
With
.BR "\-\-target metal" ,
it rebuilds on other hardware: the original sizes, the disk named by whoever
runs it, and the guest-only packages removed. Either way the sheet covers
what does not move: network interface names and MAC addresses, LUKS keys
held by the old machine's TPM, Secure Boot keys and the hibernation
resume device.
.SH IMAGES AND INDEXES
An image is an ordinary POSIX tar archive of three parts, each compressed on
its own:
.PP
.RS
.nf
restate/index.json.gz
restate/kit.tar.gz
restate/files.tar.gz
.fi
.RE
.PP
The index is first, and is all that
.BR verify ,
.BR diff ,
.BR packages ,
.B buildsheet
and
.B autoinstall
read. The kit holds what a reinstall needs before anything else \-
.IR /etc/apt ,
and the packages the image keeps that no repository has \- so that it can
be had in seconds. The files part holds every kept file, directory, symbolic
link and FIFO under
.IR restate/files ,
with its owner, mode and times (the kit's members too). The outer archive is
not compressed, so tar skips the parts it is not asked for rather than
reading them, and each part unpacks by hand when nothing else is available:
.PP
.RS
.nf
tar \-xOf IMAGE restate/files.tar.gz |
    tar \-xzpf \- \-\-numeric\-owner \-C / \-\-strip\-components=2
.fi
.RE
.PP
State is always kept; baseline content only with
.BR \-\-baseline\-content ,
because the operating system can supply it again. An image made before 1.1
is one gzip'd tar with
.I restate/index.json
first and the files after it, and is still read.
.PP
The index is JSON, one entry per line, sorted by path. Each entry records
the full
.I path
and its last component
.IR name ;
the
.I type
(file, directory, symlink, char, block, fifo) and
.IR class ;
the permission
.I mode
as an octal string; the numeric
.IR uid " and " gid
and the
.IR user " and " group
names behind them; the
.IR size ,
link count
.IR nlink ,
.IR device " and " inode ;
a device's
.IR rdev ;
the access, modification, status-change and birth times
.IR atime ,
.IR mtime ,
.IR ctime " and " btime ,
to the nanosecond in ISO 8601 UTC, with
.I btime
null where the filesystem keeps no birth time; a regular file's
.I sha256
digest, with
.B """unreadable"": true"
where it could not be read; a symbolic link's
.IR target ;
and, in an image, where the content is
.IR stored .
.PP
A JSON string must be UTF-8 and a file name need not be. A path or target
that is not valid UTF-8 is written lossily under its own key, for reading,
and exactly under the same key with
.B _base64
appended, which is what is read back.
.PP
The digest is SHA-256 rather than MD5: an MD5 collision can be made to
order, so two different files could compare equal. Every path read from an
index must be absolute and clean, with no
.BR . ,
.B ..
or empty component, or the index is rejected.
.PP
An image or index written with
.B \-\-output
is created with mode 0600, because it is a map of everything on the machine
and who owns it, and it replaces the previous file only once it is complete.
Reading a file to hash or keep it does not change its access time on Linux,
where
.B O_NOATIME
is available to the file's owner and to root; reading a symbolic link's
target does, and nothing can prevent that.
.PP
A file written to while it is copied \- a log, usually \- is kept as it
was when its copy began, with a digest of what was kept, and a warning says
so; it is not counted as unreadable. One that is cut short while copied, or
whose reading fails, is recorded as unreadable, and the exit status is 3.
.PP
An image can hold keys \- a LUKS key file under
.IR /etc ,
SSH host keys, TLS private keys \- so
.B \-\-encrypt\-to
encrypts it to the OpenPGP public key in a file
.RB ( "gpg \-\-export \-o key.gpg" ),
once for each recipient. Only a public key is needed to capture, so a
capture can run unattended with no passphrase anywhere, and only the holder
of a matching secret key can read the image.
.BR gpg (1)
runs in the same pipe as gzip, in an empty GnuPG home of its own that is
removed afterwards, once for each part of the image: each is an ordinary
OpenPGP message, its name ending in
.IR .gpg ,
that
.B gpg \-d
reads anywhere, and reading the index decrypts only the index. One thing is
not encrypted: while the tree is walked, the
content being kept is staged in an unlinked temporary file in the image's
directory, because the index comes first in the image and is not complete
until the walk is. It is never visible by name and is gone when
restate exits, but its blocks were written; where even that must not
happen, write the image to encrypted storage or a tmpfs.
.BR diff ,
.BR verify ,
.BR installer ,
.B buildsheet
and
.B autoinstall
read an encrypted image directly, decrypting with the invoking user's own
GnuPG keyring.
.PP
An image is compressed by
.BR pigz (1)
where it is installed \- the same gzip format, on every core, several times
faster on a large image \- and by gzip, with a warning saying so, where it
is not. Each is run as a separate process from a fixed path, never through
.BR PATH ;
see
.BR "SECURITY CONSIDERATIONS" .
CLASSES

  printf '.SH EXIT STATUS\n'
  section "Exit status" | while IFS= read -r line; do
    code="$(printf '%s' "$line" | sed -E 's/^ +([0-9]+) .*/\1/')"
    text="$(printf '%s' "$line" | sed -E 's/^ +[0-9]+ +//' | escape_roff)"
    printf '.TP\n.B %s\n%s\n' "$code" "$text"
  done

  cat <<'ENVIRONMENT'
.SH ENVIRONMENT
.TP
.B SOURCE_DATE_EPOCH
When set to a number of seconds since the epoch, used as the creation time
written into an index instead of the clock.
.TP
.BR https_proxy ", " all_proxy ", " no_proxy
And their upper-case forms: passed to
.BR curl (1)
by
.BR "restate installer fetch" ,
for a machine that reaches the Internet through a proxy.
.TP
.BR HOME ", " GNUPGHOME ", " GPG_TTY ", " TERM ", " DISPLAY ", " WAYLAND_DISPLAY ", " XDG_RUNTIME_DIR ", " DBUS_SESSION_BUS_ADDRESS
Passed to
.BR gpg (1)
when an encrypted image is read, so it finds the secret key in the invoking
user's GnuPG home and can ask for its passphrase. Under
.BR sudo (8)
that is root's home, unless
.B GNUPGHOME
names another.
.PP
No other variable reaches a program
.B restate
runs.
ENVIRONMENT

  cat <<'USECASES'
.SH USE CASES
.TP
.B What changed on this server?
Capture on a schedule, then
.B verify
an image against the machine as it is now, or
.B diff
two images, to see what was added, deleted or modified \- content, mode,
owner or link target \- without the noise of timestamps.
.TP
.B Why does this one behave differently?
.B scan
two machines that are meant to be identical and
.B diff
the indexes.
.TP
.B What did that installer do?
Capture before and after installing software or running a
configuration-management job, and
.B diff
the two.
.TP
.B What is on this machine?
.B restate machine
and an index document a machine before it is decommissioned, handed over or
audited: hardware, firmware, disk layout, encryption, mounts, and every file
with its owner, mode, times and SHA-256.
.TP
.B A safety net before an upgrade
Capture before a release upgrade, keep the image, and
.B diff
afterwards.
.TP
.B Rebuilding after a dead disk
.B restate buildsheet
and
.B restate autoinstall
turn an image's machine description into the steps that rebuild the disk
layout and reinstall onto it, by hand or unattended; the image then puts
the files back. Packages installed since the original install still have to
be reinstalled by hand in this version.
.TP
.B Into a virtual machine, or back onto hardware
The same, with
.B \-\-target vm
or
.BR "\-\-target metal" :
volumes resized to what they use, the VM itself defined, and the drivers,
interface names, TPM-held keys and hardware-only packages accounted for.
.PP
Planned, and described in the project's ROADMAP: the package inventory that
makes a rebuild complete; stamping out many copies of one machine, each
with its own host name, address, machine-id and SSH host keys; and
air-gapped rebuilds.
USECASES

  printf '.SH EXAMPLES\n'
  section "Examples" | while IFS= read -r line; do
    printf '.PP\n.RS\n.nf\n%s\n.fi\n.RE\n' "$(printf '%s' "${line#  }" | escape_roff)"
  done

  cat <<'TRAILER'
.SH FILES
.TP
.I /var/cache/restate/installers/VENDOR/RELEASE/
Where
.B restate installer fetch
keeps installation images, with the
.I SHA256SUMS
and signature they were checked against
.RI ( /Library/Caches/restate/installers
on macOS). Anything here can be deleted; it is fetched again when needed.
.PP
Otherwise
.B restate
keeps no files of its own: no configuration, no database, no directory of
images. It writes only what
.B \-\-output
names, and reads only the tree it is given and the files named on its
command line. A site's rules live wherever the administrator keeps them and
are passed with
.BR \-\-rules .
.SH SECURITY CONSIDERATIONS
A complete scan reads every file on the machine and so runs as root. It opens
everything with
.B O_NOFOLLOW
relative to its parent directory, and refuses a file or directory that is not
the one it examined a moment earlier, so an unprivileged user cannot redirect
it by swapping a directory for a symbolic link mid-scan.
.PP
An image or index is input when it is read back. The JSON and tar parsers
are strict, bounded and fuzzed, and they reject any path that is not clean
and absolute, so that an index cannot name a location outside the tree it
describes.
.PP
.B restate
runs five programs, each for something it should not do itself:
.BR gzip (1),
.BR pigz (1)
(the same compression on every core, used in place of gzip to write an
image where it is installed),
.BR curl (1),
.BR gpgv (1)
and
.BR gpg (1).
Each is run from a fixed absolute path \-
.IR /usr/bin ,
then
.I /usr/local/bin
for all but gzip, then
.I /bin
\- never through
.BR PATH ,
and only if root owns both the program and its directory and nobody else
can write to them, because restate runs as root and a program another user
could replace would run as root too. They are started with
.BR posix_spawn (3),
with no shell, and with an environment of
.BR PATH ,
.B LC_ALL
and what that one program needs (see
.BR ENVIRONMENT ).
restate itself opens no network connection;
curl is held to HTTPS, redirects included, and ignores
.IR ~/.curlrc .
Nothing downloaded is used until its checksum has been verified against a
signature by the pinned vendor key.
.SH SEE ALSO
.BR find (1),
.BR cryptsetup (8),
.BR curl (1),
.BR gpg (1),
.BR gpgv (1),
.BR gzip (1),
.BR mdadm (8),
.BR mtree (8),
.BR tar (1),
.BR rsync (1),
.BR sfdisk (8),
.BR sha256sum (1),
.BR vgcfgrestore (8),
.BR virt-install (1),
.BR dpkg (1),
.BR pkg (8),
.BR pkg_info (1)
.SH AUTHORS
Bryan C. Everly.
.SH BUGS
This is the first stage of a larger tool. It captures and compares state; it
does not yet compare baseline files against the digests the package manager
already holds \- dpkg on Debian and Ubuntu, rpm on Red Hat and its relatives,
pkg on FreeBSD, the package databases of OpenBSD and NetBSD, and the sealed
system volume and installer receipts on macOS \- record extended attributes,
ACLs or file capabilities, keep hard links as links, or restore an image
itself. The project's ROADMAP lists what comes next.
.PP
Report bugs at
.UR https://github.com/bceverly/restate/issues
.UE .
TRAILER
} > "$TMP"

# The page with the date in its .TH line blanked out -- the date only, not
# the line. The same line carries the version, and ignoring the whole of it
# once let a release go out with the previous version in the manpage's
# footer, because a page differing only there was judged unchanged.
strip_date() { sed 's/^\(\.TH RESTATE 8 \)"[^"]*"/\1"DATE"/' "$1"; }

if [ "$CHECK" -eq 1 ]; then
  [ -f "$OUTPUT" ] || { echo "gen-man.sh: $OUTPUT does not exist; run 'make man'" >&2; exit 1; }
  strip_date "$OUTPUT" > "$TMP.a"
  strip_date "$TMP" > "$TMP.b"
  if ! diff -u "$TMP.a" "$TMP.b" > /dev/null; then
    echo "gen-man.sh: $OUTPUT is out of date with '$BINARY --help'." >&2
    diff -u "$TMP.a" "$TMP.b" | head -40 >&2
    echo "Regenerate it with 'make man' and commit the result." >&2
    exit 1
  fi
  exit 0
fi

# Only rewritten when the content changed, so `make build` does not touch a
# committed file -- or its date -- for nothing.
if [ -f "$OUTPUT" ]; then
  strip_date "$OUTPUT" > "$TMP.a"
  strip_date "$TMP" > "$TMP.b"
  if cmp -s "$TMP.a" "$TMP.b"; then
    touch "$OUTPUT"
    exit 0
  fi
  # The content changed, so the date should say so.
  sed -i.bak "s/^\.TH RESTATE 8 \"[^\"]*\"/.TH RESTATE 8 \"$DATE\"/" "$TMP" && rm -f "$TMP.bak"
fi
mkdir -p "$(dirname "$OUTPUT")"
cat "$TMP" > "$OUTPUT"
