#!/usr/bin/env bash
#
# Copyright (c) 2026 Bryan C. Everly
# SPDX-License-Identifier: BSD-2-Clause
#
# Generate man/restate.8 from the program's own --help output.
#
#   scripts/gen-man.sh BINARY OUTPUT        write the manpage
#   scripts/gen-man.sh --check BINARY PAGE  fail if the committed page is stale
#
# The commands, options, exit statuses and examples in the manpage are not
# maintained by hand: they are read out of `restate --help`, which is itself
# generated from src/commands.def and src/options.def. Adding an option updates
# the parser, the help, the manpage and the README together, and `make lint`
# runs the --check mode so a page that was not regenerated fails rather than
# documenting an option that no longer exists.
#
# Only the prose sections below are written here: the part a generator cannot
# invent, and short enough to keep correct by reading it.
#
# The date in the .TH line is the one thing --check ignores, and a page whose
# content has not changed keeps the date it already has. A date taken from a
# file's mtime changes on every fresh checkout, and a freshness check that
# fails on a clean clone is a check people learn to ignore.
set -euo pipefail

CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
  shift
fi

BINARY="${1:?usage: gen-man.sh [--check] BINARY OUTPUT}"
OUTPUT="${2:?usage: gen-man.sh [--check] BINARY OUTPUT}"

[ -x "$BINARY" ] || { echo "gen-man.sh: $BINARY is not executable" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# The VERSION file, not --version: a working build reports "-dev", and the
# manpage is a committed file that names the release.
VERSION="$(cat "$REPO_ROOT/VERSION")"

# Today, unless the existing page carries a date already; see above.
DATE="$(date -u '+%B %d, %Y')"
DATE="${DATE/ 0/ }"
if [ -f "$OUTPUT" ]; then
  OLD_DATE="$(sed -n 's/^\.TH RESTATE 8 "\([^"]*\)".*/\1/p' "$OUTPUT" | head -1)"
  [ -n "$OLD_DATE" ] && KEEP_DATE="$OLD_DATE"
fi

# roff treats a leading '.' or '\'' as a request, and a bare '-' as a hyphen
# rather than the minus an option needs.
escape_roff() {
  sed -e 's/\\/\\e/g' -e 's/-/\\-/g' -e 's/^[.'"'"']/\\\&&/'
}

HELP="$("$BINARY" --help)"

# The lines of one section of --help, between its heading and the next blank
# line, with wrapped continuation lines joined back onto their entry.
section() {
  printf '%s\n' "$HELP" | awk -v want="$1" '
    $0 == want ":" { on = 1; next }
    on && /^$/     { exit }
    on {
      if ($0 ~ /^                    /) {     # a continuation line
        sub(/^ +/, "")
        entry = entry " " $0
        next
      }
      if (entry != "") print entry
      entry = $0
    }
    END { if (entry != "") print entry }
  '
}

# "  term   description" -> .TP entries. Terms are bold, with an argument after
# "=" or a space in italics.
entries() {
  local kind="$1"
  while IFS= read -r line; do
    local term desc
    term="$(printf '%s' "$line" | sed -E 's/^ +//; s/ {2,}.*$//')"
    desc="$(printf '%s' "$line" | sed -E 's/^ +[^ ].*[^ ] {2,}//; s/^ +//' | escape_roff)"
    if [ "$kind" = "option" ]; then
      term="$(printf '%s' "$term" | escape_roff \
              | sed -E 's/(\\-\\-[a-z-]+)=([A-Z]+)/\\fB\1\\fR=\\fI\2\\fR/; s/^(\\-[A-Za-z]),/\\fB\1\\fR,/; s/^(\\-\\-[a-z-]+)$/\\fB\1\\fR/')"
    else
      local name args
      name="${term%% *}"
      args=""
      [ "$name" != "$term" ] && args=" \\fI${term#* }\\fR"
      term="\\fB${name}\\fR${args}"
    fi
    printf '.TP\n%s\n%s\n' "$term" "$desc"
  done
}

TMP="$(mktemp)"
trap 'rm -f "$TMP" "$TMP.a" "$TMP.b"' EXIT

{
  cat <<HEADER
.\" Generated by scripts/gen-man.sh from \`restate --help\` -- do not edit by hand.
.\" Run \`make man\` after changing src/options.def or src/commands.def.
.\"
.\" Copyright (c) 2026 Bryan C. Everly
.\" SPDX-License-Identifier: BSD-2-Clause
.TH RESTATE 8 "${KEEP_DATE:-$DATE}" "restate $VERSION" "System Manager's Manual"
.nh
.SH NAME
restate \- record what makes a machine different from its baseline
.SH SYNOPSIS
.B restate
.RI [ option ...]
.I command
.RI [ argument ...]
.SH DESCRIPTION
.B restate
records what makes this machine different from a fresh install of its
operating system, so that after the disk is wiped and the system reinstalled,
the difference can be put back.
.PP
A full backup copies every file. Most of those files came from the operating
system or its packages and can be fetched again; what cannot be fetched again
is the configuration, the data and the local changes. That difference is
usually a small fraction of the disk, and it is what
.B restate
records.
.PP
Every path is given a class by a list of rules (see
.BR CLASSES " and " RULES
below), and
.B capture
walks the tree writing an
.IR image :
a gzip'd tar holding an
.I index
of every recorded path and the content of everything worth keeping (see
.BR "IMAGES AND INDEXES" ).
.B scan
writes the index alone. Two images or indexes can be compared with
.BR diff ,
and either compared against the tree as it is now with
.BR verify .
.PP
The walk never follows a symbolic link, never opens a path longer than one
component, and checks every directory and file it opens against what it was
told it would find, so that a tree being changed underneath it cannot steer it
somewhere else.
.SH COMMANDS
Options may appear before or after the command.
HEADER

  section "Commands" | entries command

  printf '.SH OPTIONS\n'
  section "Options" | entries option

  cat <<'CLASSES'
.SH CLASSES
.TP
.B ephemeral
Runtime state with no meaning after a reboot:
.IR /proc ,
.IR /run ,
.IR /tmp ,
process ID files and sockets. Never recorded, and never descended into.
.TP
.B expendable
Could be kept, but a rebuilt machine does not need it: caches, downloaded
packages, snap images, logs. Not recorded unless
.B \-\-all
is given.
.TP
.B baseline
Supplied by the operating system or its packages:
.IR /usr ,
the package database, the kernel. Recorded with content digests, so that a
comparison against what the vendor shipped can tell which of these files were
changed locally.
.TP
.B state
What makes this machine this machine:
.IR /etc ,
.IR /home ,
.IR /root ,
.IR /var/lib ,
.IR /usr/local .
Always recorded. A path that no rule covers is state: a file nobody meant to
keep costs some space, a file nobody meant to lose costs the restore.
.SH RULES
A rule is a class and a pattern, one per line:
.PP
.RS
.nf
state       /srv
expendable  /srv/cache    # comments start with a '#' after a space
ephemeral   *.sock
.fi
.RE
.PP
The
.B last
rule that covers a path decides its class, as in
.BR gitignore (5),
so a site rules file given with
.B \-\-rules
overrides any built-in rule. A rule covers the path it names and everything
beneath it. Because an ephemeral or expendable directory is not descended
into, no later rule can rescue something inside one; classify the directory as
state and its unwanted children as expendable instead.
.PP
In a pattern,
.B *
matches any run of characters except
.BR / ,
.B **
matches any run including
.BR / ,
.B **/
matches zero or more whole directories,
.B ?
matches one character except
.BR / ,
and a backslash makes the next character literal. A pattern that does not
begin with
.B /
matches at any depth.
.PP
The built-in rules are chosen by operating system: linux, freebsd, openbsd,
netbsd and darwin.
.B restate rules
prints them in this format, with the reason for each, so that a site that
disagrees can save them, edit them, and run with
.BR "\-N \-R" " file" .
.SH IMAGES AND INDEXES
An image is an ordinary gzip'd POSIX tar archive:
.PP
.RS
.nf
restate/index.json
restate/files/etc/hosts
restate/files/etc/ssh/sshd_config
\&...
.fi
.RE
.PP
.I index.json
is always the first member, so it can be read without the rest. Under
.I restate/files
is every kept file, directory, symbolic link and FIFO with its owner, mode
and times, so that
.B tar \-xzpf
can unpack an image by hand when nothing else is available. State is always
kept; baseline content only with
.BR \-\-baseline\-content ,
because the operating system can supply it again.
.PP
The index is JSON, one entry per line, sorted by path. Each entry records
the full
.I path
and its last component
.IR name ;
the
.I type
(file, directory, symlink, char, block, fifo) and
.IR class ;
the permission
.I mode
as an octal string; the numeric
.IR uid " and " gid
and the
.IR user " and " group
names behind them; the
.IR size ,
link count
.IR nlink ,
.IR device " and " inode ;
a device's
.IR rdev ;
the access, modification, status-change and birth times
.IR atime ,
.IR mtime ,
.IR ctime " and " btime ,
to the nanosecond in ISO 8601 UTC, with
.I btime
null where the filesystem keeps no birth time; a regular file's
.I sha256
digest, with
.B """unreadable"": true"
where it could not be read; a symbolic link's
.IR target ;
and, in an image, where the content is
.IR stored .
.PP
A JSON string must be UTF-8 and a file name need not be. A path or target
that is not valid UTF-8 is written lossily under its own key, for reading,
and exactly under the same key with
.B _base64
appended, which is what is read back.
.PP
The digest is SHA-256 rather than MD5: an MD5 collision can be made to
order, so two different files could compare equal. Every path read from an
index must be absolute and clean, with no
.BR . ,
.B ..
or empty component, or the index is rejected.
.PP
An image or index written with
.B \-\-output
is created with mode 0600, because it is a map of everything on the machine
and who owns it, and it replaces the previous file only once it is complete.
Reading a file to hash or keep it does not change its access time on Linux,
where
.B O_NOATIME
is available to the file's owner and to root; reading a symbolic link's
target does, and nothing can prevent that.
.PP
gzip is run as a separate process, from
.I /usr/bin/gzip
or
.IR /bin/gzip ,
never through
.BR PATH .
CLASSES

  printf '.SH EXIT STATUS\n'
  section "Exit status" | while IFS= read -r line; do
    code="$(printf '%s' "$line" | sed -E 's/^ +([0-9]+) .*/\1/')"
    text="$(printf '%s' "$line" | sed -E 's/^ +[0-9]+ +//' | escape_roff)"
    printf '.TP\n.B %s\n%s\n' "$code" "$text"
  done

  cat <<'ENVIRONMENT'
.SH ENVIRONMENT
.TP
.B SOURCE_DATE_EPOCH
When set to a number of seconds since the epoch, used as the creation time
written into an index instead of the clock.
ENVIRONMENT

  printf '.SH EXAMPLES\n'
  section "Examples" | while IFS= read -r line; do
    printf '.PP\n.RS\n.nf\n%s\n.fi\n.RE\n' "$(printf '%s' "${line#  }" | escape_roff)"
  done

  cat <<'TRAILER'
.SH SECURITY CONSIDERATIONS
A complete scan reads every file on the machine and so runs as root. It opens
everything with
.B O_NOFOLLOW
relative to its parent directory, and refuses a file or directory that is not
the one it examined a moment earlier, so an unprivileged user cannot redirect
it by swapping a directory for a symbolic link mid-scan.
.PP
An image or index is input when it is read back. The JSON and tar parsers
are strict, bounded and fuzzed, and they reject any path that is not clean
and absolute, so that an index cannot name a location outside the tree it
describes.
.SH SEE ALSO
.BR find (1),
.BR gzip (1),
.BR mtree (8),
.BR tar (1),
.BR rsync (1),
.BR sha256sum (1),
.BR dpkg (1),
.BR pkg (8),
.BR pkg_info (1)
.SH AUTHORS
Bryan C. Everly.
.SH BUGS
This is the first stage of a larger tool. It captures and compares state; it
does not yet compare baseline files against the package manager's own digests,
record extended attributes, ACLs or file capabilities, keep hard links as
links, or restore an image itself. The project's ROADMAP lists what comes
next.
.PP
Report bugs at
.UR https://github.com/bceverly/restate/issues
.UE .
TRAILER
} > "$TMP"

# Everything except the .TH line, which carries the date.
strip_date() { grep -v '^\.TH RESTATE 8 ' "$1" || true; }

if [ "$CHECK" -eq 1 ]; then
  [ -f "$OUTPUT" ] || { echo "gen-man.sh: $OUTPUT does not exist; run 'make man'" >&2; exit 1; }
  strip_date "$OUTPUT" > "$TMP.a"
  strip_date "$TMP" > "$TMP.b"
  if ! diff -u "$TMP.a" "$TMP.b" > /dev/null; then
    echo "gen-man.sh: $OUTPUT is out of date with '$BINARY --help'." >&2
    diff -u "$TMP.a" "$TMP.b" | head -40 >&2
    echo "Regenerate it with 'make man' and commit the result." >&2
    exit 1
  fi
  exit 0
fi

# Only rewritten when the content changed, so `make build` does not touch a
# committed file -- or its date -- for nothing.
if [ -f "$OUTPUT" ]; then
  strip_date "$OUTPUT" > "$TMP.a"
  strip_date "$TMP" > "$TMP.b"
  if cmp -s "$TMP.a" "$TMP.b"; then
    touch "$OUTPUT"
    exit 0
  fi
  # The content changed, so the date should say so.
  sed -i.bak "s/^\.TH RESTATE 8 \"[^\"]*\"/.TH RESTATE 8 \"$DATE\"/" "$TMP" && rm -f "$TMP.bak"
fi
mkdir -p "$(dirname "$OUTPUT")"
cat "$TMP" > "$OUTPUT"
