#!/usr/bin/env bash
#
# Copyright (c) 2026 Bryan C. Everly
# SPDX-License-Identifier: BSD-2-Clause
#
# Regenerate .github/requirements/semgrep.txt: the newest semgrep, and every
# package it pulls in at the newest version semgrep accepts, each pinned by
# version and hash for `pip install --require-hashes` in the Security workflow.
#
#   scripts/lock-semgrep.sh
#
# Run it when Dependabot proposes a semgrep bump, or when an advisory names a
# locked package. The whole set is resolved together, because the packages
# under semgrep are semgrep's to choose: bumped one at a time they slip past its
# limits, and pip then "resolves" that by installing a far older semgrep.
#
# The resolve targets the CI runner (Python 3.12, x86-64 Linux), not this
# machine. It needs uv, or pipx to run uv without installing it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT=".github/requirements/semgrep.txt"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if command -v uv > /dev/null 2>&1; then
  UV=(uv)
elif command -v pipx > /dev/null 2>&1; then
  UV=(pipx run uv)
else
  echo "lock-semgrep.sh: needs uv or pipx (sudo apt install pipx)" >&2
  exit 1
fi

echo semgrep > "$WORK/semgrep.in"
"${UV[@]}" pip compile "$WORK/semgrep.in" --upgrade --generate-hashes --no-header --quiet \
  --python-version 3.12 --python-platform x86_64-unknown-linux-gnu -o "$WORK/lock.txt"

{
  cat <<'HEADER'
# Copyright (c) 2026 Bryan C. Everly
# SPDX-License-Identifier: BSD-2-Clause
#
# semgrep for the Security workflow, every package pinned by version and hash
# so CI installs exactly these files (pip --require-hashes) and nothing a
# compromised index could substitute. Generated by scripts/lock-semgrep.sh for
# the runner's Python 3.12 on x86-64 Linux -- regenerate it with that script
# rather than editing it, so the whole set stays one consistent resolve.
#
# Dependabot proposes semgrep bumps only; see .github/dependabot.yml.
HEADER
  # The input file's temporary path, in uv's "via" comments, means nothing here.
  sed "s|$WORK/semgrep.in|semgrep.in|g" "$WORK/lock.txt"
} > "$OUT"

echo "$OUT: $(grep -c '^[a-z0-9]' "$OUT") packages, $(grep -o '^semgrep==[^ ]*' "$OUT")"
